version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-server
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis-data:/data

volumes:
  redis-data:
